spring:
  jpa:
    properties:
      hibernate.jdbc.time_zone: UTC
    hibernate:
      naming:
        physical-strategy: com.glinboy.jpress.configuration.PrefixPhysicalNamingStrategy
  profiles:
    active: dev
  liquibase:
    change-log: classpath:config/liquibase/master.xml
server:
  port: 8181